export const PLAYLISTS =[
    {
        id: 1,
        name:"Tus me gusta",
        imgUrl:'https://misc.scdn.co/liked-songs/liked-songs-300.png',
        duration: "39 min 26 seg",
        creator: "Spotify",
        songs:[
            {
                id: 1,
                name:"Yonaguni",
                description:"descripcion",
                imgUrl:'https://images.genius.com/573a07cba6e81c8bf69f279565093eca.1000x1000x1.png',
                duration: "3 min 26 seg",
                artist: "Bad Bunny",
                lyrics: "Aunque sé que no debo, ey Pensar en ti, bebé, pero cuando bebo Me viene tu nombre, tu cara Tu risa y tu pelo, ey Dime dónde tú está', que yo por ti cojo un vuelo Y a Yonaguni le llego, ey No me busque' en Instagram Mami, búscame en casa Pa' que vea' lo que pasa, ey Si tú me prueba', te casa', ey Ese cabrón ni te abraza Y yo loco por tocarte Pero ni me atrevo a textearte Tú con cualquier outfit la parte' Mami, tú ere' aparte Shorty, tiene' un culo bien grande, eh De-demasiao' grande Y yo lo tengo estudiao', ya mismo me gradúo Y en la cara me lo tatúo Vi que viste mi story y subiste una pa' mí Yo que me iba a dormir, ey En la disco habían mil Y yo bailando contigo en mi mente Aunque sé que no debo Pensar en ti, bebé, pero cuando bebo Me viene tu nombre, tu cara Tu risa y tu pelo, ey Dime dónde tú está', que yo por ti cojo un vuelo Y a Yonaguni le llego",
            },
            {
                id: 2,
                name:"Sunflower",
                description:"descripcion",
                imgUrl:'https://img.discogs.com/Kh2S37VokmxgBwElbFnWy2bCreg=/fit-in/600x600/filters:strip_icc():format(webp):mode_rgb():quality(90)/discogs-images/R-13427539-1558851956-3506.jpeg.jpg',
                duration: "2 min 38 seg",
                artist: "Post Malone",
                lyrics: "Ayy, ayy, ayy, ayy (ooh) Ooh, ooh, ooh, ooh (ooh) Ayy, ayy Ooh, ooh, ooh, ooh Needless to say, I keep her in check She was a bad-bad, nevertheless (yeah) Callin' it quits now, baby, I'm a wreck (wreck) Crash at my place, baby, you're a wreck (wreck) Needless to say, I'm keeping her in check She was all bad-bad, nevertheless Callin' it quits now, baby, I'm a wreck Crash at my place, baby, you're a wreck Thinkin' in a bad way, losin' your grip Screamin' at my face, baby, don't trip Someone took a big L, don't know how that felt Lookin' at you sideways, party on tilt Ooh-ooh-ooh Some things you just can't refuse She wanna ride me like a cruise And I'm not tryna lose Then you're left in the dust Unless I stuck by ya You're the sunflower I think your love would be too much Or you'll be left in the dust Unless I stuck by ya You're the sunflower You're the sunflower",
            },
            {
                id: 3,
                name:"Burying the Dead",
                description:"descripcion",
                imgUrl:'https://i.scdn.co/image/ab67616d00001e0259f76b3f04a9344363d143e5',
                duration: "2 min 16 seg",
                artist: "Kevin Kiner",
                lyrics: "Instrumental",
            },
            {
                id: 4,
                name:"Shinzo wo Sasageyo!",
                description:"descripcion",
                imgUrl:'https://3.bp.blogspot.com/-wCq5usd3fj0/WO3tCp0Bt9I/AAAAAAAAA8Y/_Y3R413h0qcfzIIFgDm_J9ZPjzNMHwcUwCLcB/s1600/tsujo_w660.jpg',
                duration: "5 min 41 seg",
                artist: "Linked Horizon",
                lyrics: "これ以上の地獄はないだろうと信じたかった されど人類最悪の日はいつも唐突に 扉を叩く音は絶えず酷く無作法で 招かれざる災厄の灯は悪夢のように 過ぎし日を裏切る者 奴らは駆逐すべき敵だ あの日どんな顔で瞳で俺達を見つめていた 何を捨てれば悪魔をも凌げる？ 命さえ 魂さえ 決して惜しくなどはない 捧げよ！ 捧げよ！ 心臓を捧げよ！ 全ての犠牲は今、この瞬間のために 捧げよ！ 捧げよ！ 心臓を捧げよ！ 進むべき未来を その手で切り拓け！ 過ぎし日追い詰める者 奴らは憎悪をすべき敵だ あの日どんな声で言葉で俺たちを騙っていた？ 何を学べば悪魔をも屠れる 技術でも戦術でも 全て無駄になどにしない",
            },
            {
                id: 5,
                name:"Gangsta's Paradise",
                description:"descripcion",
                imgUrl:'https://images.genius.com/691b44047ee0d7b8ef1ca842167dd4d6.300x300x1.jpg',
                duration: "4 min 0 seg",
                artist: "Coolio",
                lyrics: "As I walk through the valley of the shadow of death I take a look at my life and realize there's nothin' left 'Cause I've been blastin' and laughin' so long that Even my momma thinks that my mind is gone But I ain't never crossed a man that didn't deserve it Me be treated like a punk, you know that's unheard of You better watch how you talkin' and where you walkin' Or you and your homies might be lined in chalk I really hate to trip, but I gotta loc As they croak, I see myself in the pistol smoke Fool, I'm the kinda G the little homies wanna be like On my knees in the night, sayin' prayers in the streetlight Been spendin' most their lives Livin' in a gangsta's paradise Been spendin' most their lives Livin' in a gangsta's paradise Keep spendin' most our lives Livin' in a gangsta's paradise Keep spendin' most our lives Livin' in a gangsta's paradise",
            },

        ]
    },
    {
        id: 2,
        name:"Música Relax",
        imgUrl:'https://media-cdn.tripadvisor.com/media/photo-s/14/f9/e4/e5/relax.jpg',
        duration: "7 hrs 55 min",
        creator: "Helio Barriga Obregon",
        songs:[
            {
                id: 1,
                name:"Plug in Baby",
                description:"descripcion",
                imgUrl:'https://i1.sndcdn.com/artworks-eRDUI9nW0DJe-0-t500x500.jpg',
                duration: "3 min 38 seg",
                artist: "Muse",
                lyrics: "I've exposed your lies, baby The underneath no big surprise Now it's time for changing And cleansing everything To forget your love My plug in baby Crucifies my enemies When I'm tired of giving My plug in baby In unbroken virgin realities Is tired of living Don't confuse Baby you're gonna lose Your own game Change me And replace the envying To forget your love My plug in baby Crucifies my enemies When I'm tired of giving My plug in baby In unbroken virgin realities And tired of living And I've seen your loving Mine is gone",
            },
            {
                id: 2,
                name:"Horrible",
                description:"descripcion",
                imgUrl:'https://img.discogs.com/axshN6bFeOOZ-QpW5RSbiAfj84o=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-14784856-1581542543-7553.jpeg.jpg',
                duration: "3 min 41 seg",
                artist: "Vete a la Versh",
                lyrics: "Inicias la semana con un rostro amargo Horrible como todo un perdedor Te comes un cereal muy viejo Después de verte al espejo, y te preguntas si la vida te dará algo mejor Pero eres un gran fracasado Tu ano no se ha calmado Le gusta acosar a las colegas sin razón Un salario que no ha mejorado Y el amor no te ha tocado Porque tu pinche geta es una burla al corazón Y te has vuelto adicto a las novelas y redes sociales Buscando que de alguna manera Tu lonja se desaparezca en los comerciales Pero sigues siendo una golfa Te compras una tanga rosa Te paras en la esquina ofreciendo un favor Eres un pinche monstruo culero De semen estás hecho, y ni siendo una paloma te quisieron Eres horrible Eres horrible Eres horrible Eres horrible",
            },
            {
                id: 3,
                name:"Halo",
                description:"descripcion",
                imgUrl:'https://img.discogs.com/4Rclg77mzL5KZqnVVI1C8DCKYW4=/fit-in/300x300/filters:strip_icc():format(webp):mode_rgb():quality(40)/discogs-images/R-728251-1154178954.jpeg.jpg',
                duration: "4 min 22 seg",
                artist: "Martin O'Donnell",
                lyrics: "Ooohhhhhhhhhh ohh oh ohh oohh oh ohhh ohhhhhhhhhh  Ohhh ohh ohhhhhhhh Ohhh ohh ohh ohhhhhhhhhhh  Ohhh ohh ohh Ohhh ohhh ohhhhhhhh  Ohhhh ohh ohh oh Ohh ooohhhhh oohhhhhhhhhhhhhhhhhhhhh",
            },
            {
                id: 4,
                name:"Mr. Clean",
                description:"descripcion",
                imgUrl:'https://img.discogs.com/UAdeWZ6fGDyNKClt07Y4y_N14MY=/fit-in/600x610/filters:strip_icc():format(webp):mode_rgb():quality(90)/discogs-images/R-12827250-1542720309-4952.jpeg.jpg',
                duration: "3 min 31 seg",
                artist: "Yung Gravy",
                lyrics: "Gravy Mr. Sandman bring me a dream Make him the cutest that I've ever seen Give him two lips like roses and clover Then tell him that his lonesome nights are over Gravy make it splash like Pippen Shit that's nothin' (splash) Errbody call me Big Pimpin' No, I ain't bluffin' I'm with your mom in the kitchen Makin' blueberry muffins Must be Thanksgiving 'Cause your bitch want the stuffing Mr. Clean Gravy why your flow so mean? Mr. Clean Pull up with my whole damn team Mr. Clean Mr. Clean Mr. Clean Mr. Clean",
            },
            {
                id: 5,
                name:"Cowboys From Hell",
                description:"descripcion",
                imgUrl:'https://images-na.ssl-images-amazon.com/images/I/814bTMbq%2BEL._SL1500_.jpg',
                duration: "4 min 03 seg",
                artist: "Pantera",
                lyrics: "Oh, come on! Under the lights where we stand tall Nobody touches us at all Showdown, shootout, spread fear within, without We're gonna take what's ours to have Spread the word throughout the land They say bad guys wear black We're tagged and can't turn back You see us comin' And you all together run for cover We're taking over this town Here we come reach for your gun And you better listen well, my friend, you see It's been slowed down below Aimed at you, we're the cowboys from hell Deed is done again, we've won Ain't talking no tall tales friend 'Cause high noon, your doom Comin' for you we're the cowboys from hell",
            },

        ]
    },
    {
        id: 3,
        name:"Canciones Chidoris",
        imgUrl:'https://i.scdn.co/image/ab6761610000e5eb8101d13bdd630b0889acd2fd',
        duration: "5 hrs 29 min",
        creator: "Helio Barriga Obregon",
        songs:[
          {
            id: 1,
            name:"Legends Never Die",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/bcefba20509b85c1ce13ab09cff79037/500x500.jpg',
            duration: "3 min 55 seg",
            artist: "League of Legends",
            lyrics: "Legends never die When the world is calling you Can you hear them screaming out your name? Legends never die They become a part of you Every time you bleed for reaching greatness Relentless you survive They never lose hope when everything's cold And the fighting's near It's deep in their bones, they'll run into smoke When the fire is fierce Oh, pick yourself up, 'cause",
          },
          {
            id: 2,
            name:"RISE",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/4349e2eedfe96be5c76b5ad7fa13727f/500x500.jpg',
            duration: "3 min 12 seg",
            artist: "League of Legends",
            lyrics: "Welcome to the wild, no heroes and villains Welcome to the war, we've only begun, so Pick up your weapon and face it There's blood on the crown, go and take it You get one shot to make it out alive, so Higher and higher you chase it It's deep in your bones, go and take it This is your moment, now is your time, so Prove yourself and RISE, RISE Make 'em remember you RISE Push through hell and RISE, RISE They will remember you RISE",
          },
          {
            id: 3,
            name:"Warriors",
            imgUrl:'https://lastfm.freetls.fastly.net/i/u/770x0/aed5e019e5f1419ec199a6f1ec658983.jpg',
            duration: "3 min 24 seg",
            artist: "League of Legends",
            lyrics: "As a child you would wait And watch from far away But you always knew that you'd be the one That work while they all play In youth you'd lay Awake at night and scheme Of all the things that you would change But it was just a dream! Here we are, don't turn away now, We are the warriors that built this town Here we are, don't turn away now We are the warriors that built this town From dust.",
          },
          {
            id: 4,
            name:"Phoenix",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/45eecedfdf3496b8bb31831ea0e93a30/500x500.jpg',
            duration: "3 min 17 seg",
            artist: "League of Legends",
            lyrics: "What are you willing to lose? You cover your wounds, but underneath them A million voices in your head that whisper, Stop, now Another twist of the knife, turn of the screws It's all in your mind and it's fighting you Arm yourself, a storm is coming Well, kid, what you gonna do now? It's your reflection looking back to pull you down So are you gonna die today or make it out alive? You gotta conquer the monster in your head and then you'll fly Fly, phoenix, fly It's time for a new empire Go bury your demons then tear down the ceiling Phoenix, fly",
          },
          {
            id: 5,
            name:"Take Over",
            imgUrl:'https://direct.rhapsody.com/imageserver/images/alb.509670808/500x500.jpg',
            duration: "3 min 32 seg",
            artist: "League of Legends",
            lyrics: "We at the top again, now what? Heavy lay the crown, but Count us Higher than the mountain And we be up here for the long run Strap in for a long one We got everybody on one Now you're coming at the king so you better not miss And we only get stronger With everything I carry up on my back, you should paint it up with a target Why would you dare me to do it again? Come get your spoiler up ahead",
          },
        ]
    },
    {
        id: 4,
        name:"Arctic Monkeys",
        imgUrl:'https://beyondvinyl.co.uk/wp-content/uploads/2020/04/arctic-monkeys-am.jpg',
        duration: "1 hr 28 min",
        creator: "Helio Barriga Obregon",
        songs:[
            {
                id: 1,
                name:"When The Sun Goes Down",
                imgUrl:'https://www.nacionrock.com/wp-content/uploads/arctic.jpg',
                duration: "3 min 22 seg",
                artist: "Arctic Monkeys",
                lyrics: "So who's that girl there? I wonder what went wrong So that she had to roam the streets She don't do major credit cards I doubt she does receipts It's all not quite legitimate And what a scummy man Just give him half a chance I bet he'll rob you if he can Can see it in his eyes, yeah That he's got a driving ban Amongst some other offences",
              },
              {
                id: 2,
                name:"Fluorecent Adolescent",
                imgUrl:'https://m.media-amazon.com/images/I/81jUUHuNvEL._SL1425_.jpg',
                duration: "3 min 4 seg",
                artist: "Arctic Monkeys",
                lyrics: "You used to get it in your fishnets Now you only get it in your night dress Discarded all the naughty nights for niceness Landed in a very common crisis Everything's in order in a black hole Nothing seems as pretty as the past, though That Bloody Mary's lacking a Tabasco Remember when you used to be a rascal?  Oh, that boy's a slag The best you ever had The best you ever had Is just a memory and those dreams Weren't as daft as they seemed Not as daft as they seemed My love, when you dreamed them up",
              },
              {
                id: 3,
                name:"R U Mine?",
                imgUrl:'https://upload.wikimedia.org/wikipedia/commons/e/e7/%22AM%22_%28Arctic_Monkeys%29.jpg',
                duration: "3 min 22 seg",
                artist: "Arctic Monkeys",
                lyrics: "I'm a puppet on a string Tracy Island, time-travelin' diamond cutter-shaped heartaches Come to find you four in some velvet mornin' years too late She's a silver linin', lone ranger ridin' through an open space In my mind, when she's not right there beside me I go crazy 'cause here isn't where I wanna be And satisfaction feels like a distant memory And I can't help myself All I wanna ever say is, Are you mine? Well, are you mine? Are you mine? Are you mine? Oh, ah",
              },
              {
                id: 4,
                name:"I Bet You Look Good on the Dancefloor",
                imgUrl:'https://www.nacionrock.com/wp-content/uploads/arctic.jpg',
                duration: "2 min 54 seg",
                artist: "Arctic Monkeys",
                lyrics: "Stop making the eyes at me I'll stop making the eyes at you What it is that surprises me Is that I don't really want you to And your shoulders are frozen (cold as the night) Oh, but you're an explosion (you're dynamite) Your name isn't Rio, but I don't care for sand And lighting the fuse might result in a bang, b-b-bang-oh",
              },
              {
                id: 5,
                name:"Mardy Bum",
                imgUrl:'https://www.nacionrock.com/wp-content/uploads/arctic.jpg',
                duration: "2 min 55 seg",
                artist: "Arctic Monkeys",
                lyrics: "Well, now then, mardy bum I've seen your frown and it's like looking down The barrel of a gun And it goes off And out come all these words Oh, there's a very pleasant side to you A side I much prefer It's one that laughs and jokes around Remember cuddles in the kitchen, yeah To get things off the ground And it was up, up and away Oh, but it's right hard to remember that On a day like today When you're all argumentative And you've got the face on",
              },
        ]
    },
    {
        id: 5,
        name:"La Playlist Mix",
        imgUrl:'https://static.mytuner.mobi/media/tvos_radios/bbjG4U8gcs.png',
        duration: "9 hrs 15 min",
        creator: "Helio Barriga Obregon",
        songs:[
          {
            id: 1,
            name:"Contra La Pared",
            imgUrl:'https://www.oxigeno.fm/wp-content/uploads/2019/03/sean-y-balvin.png',
            duration: "3 min 44 seg",
            artist: "J Balvin",
            lyrics: "Sp 'longside J Balvin, men El negocio socio De día y de noche me llama (Night and day, leggo', biri-bam-bam-bam) Que quiere de nuevo en mi cama (Latino gang, Want inna me bed, biri-bam-bam) No fue suficiente una vez (Sean da' Paul, uh-yeah, bam-bam-bam) Ahora de día y de noche reclama (That was she said, biri-bam, ¡wuh!) Well in come the ting dem call chicks, it's for kicks and we don't play games Straight business, baby girl Tainy pon the track Hear what mi sayin' Balvin, tell 'em again (Trá)",
          },
          {
            id: 2,
            name:"El Farsante",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/6145aa97e61ec6c8f701f570f4701741/350x350.jpg',
            duration: "3 min 53 seg",
            artist: "Ozuna",
            lyrics: "Extraño tu aroma en la cama De ese que dejas cuando entras y sales Dónde quedaron los besos y todos los planes No sé si vivir o morir Me encuentro en un limbo desde que te fuiste de aquí Eres la única persona que yo quiero que se venga encima de mí Mi libertad no la quiero Tampoco la vida e' soltero Yo lo que quiero es que quieras lo mismo que todos queremos Tener una cuenta de banco con dígitos y muchos ceros Hacer el amor a diario y de paso gastar el dinero",
          },
          {
            id: 3,
            name:"Te Boté - Remix",
            imgUrl:'https://heabbi.com/wp-content/uploads/2018/04/Nio-Garcia-Ft.-Casper-Magico-Darell-Nicky-Jam-Ozuna-Te-Bote-Remix.jpg',
            duration: "6 min 57 seg",
            artist: "Ozuna",
            lyrics: "Este es el verdadero remix, baby  Paso muchas noches pensándote Yo no sé ni cómo, ni cuándo fue Pero solo sé que yo recordé Cómo te lo hacía yo aquella vez Y yo no puedo seguir solo, pero sé Que te boté  De mi vida te boté, y te boté Te di banda y te solté, yo te solté Pa'l carajo usted se fue, y usted se fue De mi vida te boté, yo te boté, yeh-yeh, mami",
          },
          {
            id: 4,
            name:"Criminal",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/122cd03379bff4566c5c39628e945393/500x500.jpg',
            duration: "3 min 51 seg",
            artist: "Ozuna",
            lyrics: "Uh oh oh oh El negrito ojos claros Ozuna Miento Si te digo que en ti no ando pensando Quisiera saber lo que estás haciendo Te llamo pero me sale ocupado, oh Tú me robaste el corazón como un criminal Bebé yo no puedo negarlo Esto que siento por ti no puede ser legal, ah",
          },
          {
            id: 5,
            name:"Phoenix",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/45eecedfdf3496b8bb31831ea0e93a30/500x500.jpg',
            duration: "3 min 17 seg",
            artist: "League of Legends",
            lyrics: "What are you willing to lose? You cover your wounds, but underneath them A million voices in your head that whisper, Stop, now Another twist of the knife, turn of the screws It's all in your mind and it's fighting you Arm yourself, a storm is coming Well, kid, what you gonna do now? It's your reflection looking back to pull you down So are you gonna die today or make it out alive? You gotta conquer the monster in your head and then you'll fly Fly, phoenix, fly It's time for a new empire Go bury your demons then tear down the ceiling Phoenix, fly",
          }
        ]
    },
    {
        id: 6,
        name:"This is Mac Miller",
        creator: "Spotify",
        imgUrl:'https://i.scdn.co/image/ab67706f00000003723228643ca262e4d71cae24',
	    duration: "4h 13m",
        songs:[
            {
                id: 1,
                name:"The Spins",
                imgUrl:'https://www.mor.bo/wp-content/uploads/2020/05/kids.jpg',
                duration: "3 min 16 seg",
                artist: "Mac Miller",
                lyrics: "Dope shit like that Jerm Oh hi Welcome back to K.I.D.S Umm, follow your dreams Yeah! Wanna get a mansion A jacuzzi, a theater to watch my movies A couple whips and lots of fancy things The kids they call the Goonies I see the future, crystal ball Mirror, mirror hangin' on the wall Who the flyest white boy of them dem all? Got your girlfriend screenin' all the calls",
              },
              {
                id: 2,
                name:"Kool Aid & Frozen Pizza",
                imgUrl:'https://www.mor.bo/wp-content/uploads/2020/05/kids.jpg',
                duration: "2 min 38 seg",
                artist: "Mac Miller",
                lyrics: "Kids Hey Kool-Aid and frozen pizza It's a work of art, I ain't talking Mona Lisa Dream of rocking crowds, see me filling up arenas This weed got me laughing like a damn hyena (ha) Yeah, I live a life pretty similar to yours Used to go to school, hang with friends and play sports Every single summer taking trips to the shore And that was all gravy but I knew I wanted more",
              },
              {
                id: 3,
                name:"Right",
                imgUrl:'https://www.mondosonoro.com/wp-content/uploads/2020/01/mac-miller-circles.jpg',
                duration: "4 min 48 seg",
                artist: "Mac Miller",
                lyrics: "Yeah, it's been a while without your face But I saw your picture on the wall the other day Too much distance, too much space You need to come back home or run along, yeah I'm waitin' for the light to change You ask me how I've been, well I'm good, I can't complain Times get harder, things get strained All I know, I don't want you gone",
              },
              {
                id: 4,
                name:"Good News",
                imgUrl:'https://www.mondosonoro.com/wp-content/uploads/2020/01/mac-miller-circles.jpg',
                duration: "5 min 42 seg",
                artist: "Mac Miller",
                lyrics: "Well this is what it look like right before you fall Stumblin' around, you've been guessin' your direction Next step you can't see at all And I don't have a name, I don't have a name, no Who am I to blame, who am I to blame though? And I cannot be changed, I cannot be changed, no Trust me, I've tried I just end up right at the start of the line Drawin' circles",
              },
              {
                id: 5,
                name:"Time",
                imgUrl:'https://media.socastsrm.com/wordpress/wp-content/blogs.dir/2162/files/2019/06/62205725_310411836503608_4657536626805029247_n.jpg',
                duration: "3 min 30 seg",
                artist: "Mac Miller",
                lyrics: "I gotta take some time to grow But I don't wanna let you go How did we get too comfortable? I gotta take some time to grow But without you, I'm miserable I think I got too comfortable We could take it to the day that I saw you On your way to the top Or we could take it to the time that I saw You lose your mind and give up Everybody gets down on luck Every time you fall I try to pick you up But I need reciprocation",
              },
        ]
    },
    {
        id: 7,
        name:"Playlist de Helio",
        creator: "Heliomenalvxd",
        imgUrl:'https://i.scdn.co/image/ab67706f00000003723228643ca262e4d71cae24',
	    duration: "3h 49m",
        songs:[
          {
            id: 1,
            name:"This is Gospel",
            imgUrl:'https://img.discogs.com/ON4dhD6b5gg3yNLhUKHw163jnGo=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-13125545-1548511063-7654.jpeg.jpg',
            duration: "3 min 7 seg",
            artist: "Panic! At The Disco",
            lyrics: "This is Gospel for the fallen ones Locked away in permanent slumber Assembling their philosophies From pieces of broken memories Oh Woah-oh (This is the beat of my heart This is the beat of my heart) Oh Woah-oh (This is the beat of my heart This is the beat of my heart) The gnashing teeth and criminal tounges Conspire against the odds But they haven't seen the best of us yet",
          },
          {
            id: 2,
            name:"Leave Me Alone",
            imgUrl:'https://i.scdn.co/image/ab67616d0000b2736ee1f56d217811025c5b90de',
            duration: "3 min 35 seg",
            artist: "I DON'T KNOW HOW BUT THE FOUND ME",
            lyrics: "Big shot, so what? Do you wanna pretend? You took the money But the money couldn't buy a friend Now I want you to leave me alone They say the devil that you know Is better than the devil that you don't Oh, you're a big shot here, but nobody else knows Now I want you to leave me alone Blind spot, take your best shot Lucky me Go fly a kite until you're tangled in the hanging tree",
          },
          {
            id: 3,
            name:"Crush",
            imgUrl:'https://img.discogs.com/CXi6jMz5bgoOgqzPt2g03WLC1KE=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13145999-1548865753-7553.jpeg.jpg',
            duration: "3 min 35 seg",
            artist: "Tessa Violet",
            lyrics: "Uh, alright I can't focus on what needs to get done I'm on notice hoping that you don't run, ah You think I'm tepid but I'm misdiagnosed 'Cause I'm a stalker I seen all of your posts, ah-ah And I'm just tryna play it cool now But that's not what I wanna do now And I'm not tryna be with you now, you now Mhm You make it difficult to not overthink",
          },
          {
            id: 4,
            name:"If You Want Blood (You've got it)",
            imgUrl:'https://m.media-amazon.com/images/I/71vsHNHr-KL._SL1500_.jpg',
            duration: "4 min 34 seg",
            artist: "AC/DC",
            lyrics: "It's criminal There ought to be a law Criminal There ought to be a whole lot more You get nothin' for nothin' Tell me who can you trust We got what you want And you got the lust If you want blood, you got it If you want blood, you got it Blood on the streets Blood on the rocks Blood in the gutter Every last drop You want blood You got it",
          },
          {
            id: 5,
            name:"18",
            imgUrl:'https://i.scdn.co/image/ab67616d00001e02e626d8740c283d5aaed3141c',
            duration: "2 min 36 seg",
            artist: "Anarbor",
            lyrics: "Eighteen, crazy Pulled up in your daddy's car You wanna move in with me Guess we're off to a heavy start Should've seen this coming from a mile away Eighteen, crazy I know what you want from me I know what you want from me",
          },
        ]
    },
    {
        id: 8,
        name:"Soft",
        creator: "David Ruiz Lara",
        imgUrl:'https://cdns-images.dzcdn.net/images/cover/b96a3116af78b8c516f18ba367e36bc0/500x500.jpg',
	    duration: "21h 32m",
        songs:[
            {
                id: 1,
                name:"Awaken",
                imgUrl:'https://cdns-images.dzcdn.net/images/cover/b96a3116af78b8c516f18ba367e36bc0/500x500.jpg',
                duration: "3 min 18 seg",
                artist: "League of Legends",
                lyrics: "The night beckons while you dream A life never lives in peace As you stand upon the edge Woven by a single thread And fate may fall down upon you While the devil is knocking Right at your door So all you restless Each night you hear the drums of war Awaken, awaken The voice begins to call you while you hunger A taste of destiny you're searching for Awaken, awaken The fight is at your door, take up the cause",
              },
              {
                id: 2,
                name:"Snow (Hey Oh)",
                imgUrl:'https://cdns-images.dzcdn.net/images/cover/7ac261fcdc9ae04f827e62e33077c6c3/264x264.jpg',
                duration: "5 min 35 seg",
                artist: "Red Hot Chilli Peppers",
                lyrics: "Come to decide that the things that I tried Were in my life just to get high on When I sit alone Come get a little known But I need more than myself this time Step from the road to the sea to the sky And I do believe that we rely on When I lay it on Come get to play it on All my life to sacrifice",
              },
              {
                id: 3,
                name:"Winter",
                imgUrl:'https://i.pinimg.com/originals/e5/12/35/e51235b2b84d98edf02e675ec17e8a46.jpg',
                duration: "4 min 2 seg",
                artist: "Khalid",
                lyrics: "II lost my heart in the nighttime She left me out in the cold She left me broken and weary Drunk off the lies she told I fell in love in the morning But when the day gets cold I'm back to life in my lonely City of El Paso",
              },
              {
                id: 4,
                name:"Skimming Stones",
                imgUrl:'https://m.media-amazon.com/images/I/81c4eUkYAQL._SL1500_.jpg',
                duration: "3 min 36 seg",
                artist: "Seafret",
                lyrics: "I'm leavin again Hopin' time doesn't mend Don't either of us know what is happenin' Theres no right time to go I will tighten this hold You know when I walk away I'll be back again If there was a place I could take ya I'd keep you safe, far away from the world Like a skimmin' stone waiting to be thrown Back to you",
              },
              {
                id: 5,
                name:"Oceans",
                imgUrl:'https://img.discogs.com/obDk-GqUX2h_B5fXMhgWoZA-95A=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-12922991-1544606338-6439.jpeg.jpg',
                duration: "3 min 36 seg",
                artist: "Seafret",
                lyrics: "I want you Yeah I want you And nothing comes close To the way that I need you I wish I can feel your skin And I want you From somewhere within It feels like there's oceans Between me and you once again We hide our emotions Under the surface and tryin' to pretend But it feels like there's oceans Between you and me",
              },
        ]
    },
    {
        id: 9,
        name:"agustoalaverga",
        creator: "Alexis Puerto",
        imgUrl:'https://i.pinimg.com/736x/ff/0d/0b/ff0d0b6ccdafa0f7818077a78af52615.jpg',
	    duration: "2h 31m",
        songs:[
            {
                id: 1,
                name:"Choke",
                imgUrl:'https://direct.rhapsody.com/imageserver/images/alb.325350587/600x600.jpg',
                duration: "3 min 16 seg",
                artist: "I DON'T KNOW HOW BUT THEY FOUND ME",
                lyrics: "Stop, drop And drag me into place And lock the fire escapes I'll break your pretty face (Nyeah, nyeah) Oh, you clever little things The sycophantic teens What a precious basket case (Nyeah, nyeah)",
              },
              {
                id: 2,
                name:"Do it All The Time",
                imgUrl:'https://direct.rhapsody.com/imageserver/images/alb.325350275/600x600.jpg',
                duration: "2 min 48 seg",
                artist: "I DON'T KNOW HOW BUT THEY FOUND ME",
                lyrics: "Ha! We're taking over the world One kiss at a time And then I'm taking your girl And I'm making her mine No reason why I'm only doing anything I want to do Because I do it all the time We're taking over the world A little victim-less crime And when I'm taking your innocence I'll be corrupting your mind",
              },
              {
                id: 3,
                name:"Young & Alive",
                imgUrl:'https://m.media-amazon.com/images/I/811lQG22CAL._SS500_.jpg',
                duration: "2 min 40 seg",
                artist: "Bazzi",
                lyrics: "Ridin' my bike like I'm too young to drive Careless and free like it's 2005 Had to chill the fuck out, take a trip outside To have fun with my friends like I'm young and alive So can I get your AOL? Hit you lot like, LOL (L) This feel like our high school days Runnin' 'round at football games (games) We ain't got a fuck or nothing, we can hold hands or somethin'",
              },
              {
                id: 4,
                name:"Rollin",
                imgUrl:'https://img.discogs.com/YLvmlbY7lejeIxt8w8rraIJvK7k=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10291060-1494760396-5981.jpeg.jpg',
                duration: "4 min 33 seg",
                artist: "Calvin Harris",
                lyrics: "I've been rollin' on the freeway I've been riding 85 I've been thinking way too much And I'm way too gone to drive I got anger in my chest I got millions on my mind And you didn't fit the picture So I guess you weren't the vibe I've been rollin' on the freeway I've been riding 85 I've been thinking way too much And I'm way too gone to drive I got anger in my chest I got millions on my mind And you didn't fit the picture So I guess you weren't the vibe",
              },
              {
                id: 5,
                name:"Freaking Out the Neighborhood",
                imgUrl:'https://cdns-images.dzcdn.net/images/cover/48dd98d88f1af797d65faf7f3e4beef7/350x350.jpg',
                duration: "2 min 54 seg",
                artist: "Mac DeMarco",
                lyrics: "Sorry, mama There are times I get carried away But please don't worry Next time I'm home, I'll still be the same And I know it's no fun When your first son Gets up to no good Starts freaking out the neighborhood Really, I'm fine Never been better, got no job on the line Sincerely, don't worry Same old boy that you hoped you would find",
              },
        ]
    },
    {
        id: 10,
        name:"Star Wars Lofi HipHop",
        creator: "Chilled Panda",
        imgUrl:'https://steamuserimages-a.akamaihd.net/ugc/1638705743367141279/E0F5142714F86C00E413C08D8FC95159DD10D796/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
	    duration: "1h 24m",
        songs:[
            {
                id: 1,
                name:"Binary Sunset",
                imgUrl:'https://i.scdn.co/image/ab67616d0000b273690bb7b4cc194a09858293e3',
                duration: "1 min 4 seg",
                artist: "Closed on Sunday",
                lyrics: "---",
              },
              {
                id: 2,
                name:"Cantina Band Theme",
                imgUrl:'https://m.media-amazon.com/images/I/71m06WI8+8S._SS500_.jpg',
                duration: "1 min 11 seg",
                artist: "CFC",
                lyrics: "---",
              },
              {
                id: 3,
                name:"the droid invasion",
                imgUrl:'https://i.scdn.co/image/ab67616d0000b273431b59af7c47935fe57ca375',
                duration: "1 min 15 seg",
                artist: "Closed on Sunday",
                lyrics: "---",
              },
              {
                id: 4,
                name:"the mandalorian",
                imgUrl:'https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/ee/b5/ab/eeb5ab4a-d4e7-1b35-804d-e7880da70914/artwork.jpg/400x400cc.jpg',
                duration: "1 min 40 seg",
                artist: "Closed on Sunday",
                lyrics: "---",
              },
              {
                id: 5,
                name:"rescue of the princess",
                imgUrl:'https://m.media-amazon.com/images/I/51qVh9mmoUS._SS500_.jpg',
                duration: "1 min 30 seg",
                artist: "Closed on Sunday",
                lyrics: "---",
              },
        ]
    },
    {
        id: 11,
        name:"Rakanral 2.0",
        creator: "David Ruiz Lara",
        imgUrl:'https://i.scdn.co/image/ab67616d0000b27304db0e3bcd166c1d6cfd81f9',
	    duration: "42h 58m",
        songs:[
            {
                id: 1,
                name:"Thunderstruck",
                imgUrl:'https://m.media-amazon.com/images/I/81qnqT8Zx-L._SL1500_.jpg',
                duration: "4 min 45 seg",
                artist: "AC/DC",
                lyrics: "Thunder, thunder, thunder, thunder Thunder, thunder, thunder, thunder Thunder, thunder I was caught In the middle of a railroad track (thunder) I looked 'round And I knew there was no turning back (thunder) My mind raced And I thought, what could I do? (Thunder) And I knew There was no help, no help from you (thunder)",
              },
              {
                id: 2,
                name:"Back in Black",
                imgUrl:'https://upload.wikimedia.org/wikipedia/commons/9/92/ACDC_Back_in_Black.png',
                duration: "4 min 15 seg",
                artist: "AC/DC",
                lyrics: "Back in black I hit the sack I've been too long I'm glad to be back. Yes, I'm Let loose From the noose That's kept me hanging about I keep lookin' at the sky 'Cause it's gettin' me high Forget the hearse cause I'll never die I got nine lives Cat's eyes Abusin' every one of them and running wild",
              },
              {
                id: 3,
                name:"Highway to Hell",
                imgUrl:'https://m.media-amazon.com/images/I/81k-3sh8OhL._SL1500_.jpg',
                duration: "3 min 28 seg",
                artist: "AC/DC",
                lyrics: "Livin' easy Lovin' free Season ticket on a one way ride Askin' nothin' Leave me be Takin' everythin' in my stride Don't need reason Don't need rhyme Ain't nothin' that I'd rather do Goin' down Party time My friends are gonna be there too I'm on the highway to hell On the highway to hell Highway to hell I'm on the highway to hell",
              },
              {
                id: 4,
                name:"If You Want Blood (You've got it)",
                imgUrl:'https://m.media-amazon.com/images/I/71vsHNHr-KL._SL1500_.jpg',
                duration: "4 min 34 seg",
                artist: "AC/DC",
                lyrics: "It's criminal There ought to be a law Criminal There ought to be a whole lot more You get nothin' for nothin' Tell me who can you trust We got what you want And you got the lust If you want blood, you got it If you want blood, you got it Blood on the streets Blood on the rocks Blood in the gutter Every last drop You want blood You got it",
              },
              {
                id: 5,
                name:"Shoot to Thrill",
                imgUrl:'https://upload.wikimedia.org/wikipedia/commons/9/92/ACDC_Back_in_Black.png',
                duration: "5 min 17 seg",
                artist: "AC/DC",
                lyrics: "All you women who want a man of the street But don't know which way you wanna turn Just keep a-comin', and put your hand out to me 'Cause I'm the one who's gonna make you burn I'm gonna take you down Oh, down, down, down So, don't you fool around I'm gonna pull it, pull it, pull the trigger",
              },
        ]
    },
    {
        id: 12,
        name:"Intrumental",
        creator: "David Ruiz Lara",
        imgUrl:'https://i.scdn.co/image/ab67616d0000b27359f76b3f04a9344363d143e5',
	    duration: "3h 50m",
        songs:[
          {
            id: 1,
            name:"Burying the Dead",
            imgUrl:'https://images-na.ssl-images-amazon.com/images/I/81qaoCLTt3L._AC_UL600_SR600,600_.jpg',
            duration: "2 min 16 seg",
            artist: "Kevin Kiner",
            lyrics: "Instrumental",
          },
          {
            id: 2,
            name:"Neighborhood",
            imgUrl:'https://is2-ssl.mzstatic.com/image/thumb/Music124/v4/64/7e/f6/647ef6d1-d035-0da3-20a6-3f7a468291de/86728da5-d8ba-4b68-88eb-b585afebe664.jpg/400x400bb.jpg',
            duration: "3 min 11 seg",
            artist: "Sans Souci",
            lyrics: "Instrumental",
          },
          {
            id: 3,
            name:"Flowers",
            imgUrl:'https://f4.bcbits.com/img/a0626843871_10.jpg',
            duration: "3 min 7 seg",
            artist: "The Deli",
            lyrics: "Instrumental",
          },
          {
            id: 4,
            name:"Sa Riera",
            imgUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdypTKO_yPo0eYn2ATp6dePz1sPSMZH9Qf0A&usqp=CAU',
            duration: "3 min 21 seg",
            artist: "TRO",
            lyrics: "I saw a white dog laying on my bed I saw a white cat beside you Will you remember me? Will you remember me? I'm getting old but I'll be gone But 'til the day that I'll be There's a lot I know you'll never see But when you do remember me? Feeling startled, losing everything Feeling startled",
          },
          {
            id: 5,
            name:"Formed by Glaciers",
            imgUrl:'https://i.ytimg.com/vi/Or0yKOUXcNo/maxresdefault.jpg',
            duration: "7 min 28 seg",
            artist: "Kubbi",
            lyrics: "Instrumental",
          },
        ]
    },
    {
        id: 13,
        name:"Electro",
        creator: "David Ruiz Lara",
        imgUrl:'https://i.scdn.co/image/ab67616d0000b273e14f11f796cef9f9a82691a7',
	    duration: "11h 5m",
        songs:[
          {
            id: 1,
            name:"Wake Me Up",
            imgUrl:'https://img.discogs.com/yp3q3ojcsuQ4RRSZsywuRGW8m9M=/fit-in/600x522/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4730632-1373680607-7059.jpeg.jpg',
            duration: "4 min 7 seg",
            artist: "Avicii",
            lyrics: "Feeling my way through the darkness Guided by a beating heart I can't tell where the journey will end But I know where to start They tell me I'm too young to understand They say I'm caught up in a dream Well life will pass me by if I don't open up my eyes Well that's fine by me So wake me up when it's all over When I'm wiser and I'm older All this time I was finding myself, and I Didn't know I was lost",
          },
          {
            id: 2,
            name:"Hey Brother",
            imgUrl:'https://m.media-amazon.com/images/I/61RmQiEH0GL._SL1417_.jpg',
            duration: "4 min 14 seg",
            artist: "Avicii",
            lyrics: "Hey brother There's an endless road to rediscover Hey sister Know that water's sweet but blood is thicker Oh, if the sky comes falling down For you There's nothing in this world I wouldn't do Hey brother Do you still believe in one another? Hey sister Do you still believe in love? I wonder",
          },
          {
            id: 3,
            name:"Broken Arrows",
            imgUrl:'https://www.alexurbanpop.com/wp-content/uploads/2015/11/Avicii-Broken-Arrows.jpg',
            duration: "3 min 52 seg",
            artist: "Avicii",
            lyrics: "You stripped your love down to the wire Fire shy and cold alone outside You stripped it right down to the wire But I see you behind those tired eyes Now as you wade through shadows that live in your heart You'll find the light that leads home Cause I see you for you and your beautiful scars So take my hand, don't let go",
          },
          {
            id: 4,
            name:"Trouble",
            imgUrl:'https://m.media-amazon.com/images/I/714s7lzZmuL._SL1500_.jpg',
            duration: "2 min 51 seg",
            artist: "Avicii",
            lyrics: "I've been a beggar and I've been a king I've been a loner and I've won the reign Losing myself just to find me again I'm a million miles smarter, but I ain't learnt a thing I've been a teacher and a student of hurt I've kept my word for whatever that's worth Never been last, but I've never been first Oh I may not be the best, but I'm far from the worst Oh I may not be the best, but I'm far from the worst",
          },
          {
            id: 5,
            name:"Addicted to You",
            imgUrl:'https://img.discogs.com/DlKiDOCuZgvKGh9HUSr1HlbkW-Y=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-5483433-1394536345-4734.jpeg.jpg',
            duration: "2 min 27 seg",
            artist: "Avicii",
            lyrics: "I don't know just how it happened I let down my guard Swore I'd never fall in love again But I fell hard Guess I should have seen it coming Caught me by surprise Wasn't looking where I was going I fell into your eyes You came into my crazy world Like a cool and cleansing wave Before I, I knew what hit me, baby You were flowing through my veins",
          },
        ]
    },
    {
        id: 14,
        name:"WOD",
        creator: "David Ruiz Lara",
        imgUrl:'https://i.scdn.co/image/ab67616d0000b273ffa830338e7bc9a8aaf44aac',
	    duration: "6h 48m",
        songs:[
          {
            id: 1,
            name:"Living My Best Life",
            imgUrl:'https://images-na.ssl-images-amazon.com/images/I/51glUemBLHL._SY445_SX342_QL70_ML2_.jpg',
            duration: "2 min 46 seg",
            artist: "Paper Kings",
            lyrics: "I got ish to do Flying through the sky in my parachute Dancing on the couch like I'm Tommy Cruise On a one man mission tryin' to see it through yeah I got the password, yeah I finally got the password Added up the numbers now the math works I got the way to make the path work All these lights turning from red to green Timing is everything, and it feels so good to shine Go and get it like!  Ay ya ya ya ya ya ya ya I'm living my best life, living my, living my best life So come and get it like Ay ya ya ya ya ya ya ya I'm living my best life, living my, living my best life",
          },
          {
            id: 2,
            name:"Fire On Up",
            imgUrl:'https://images-na.ssl-images-amazon.com/images/I/51glUemBLHL._SY445_SX342_QL70_ML2_.jpg',
            duration: "3 min 9 seg",
            artist: "Paper Kings",
            lyrics: "I'll be that silver, silver Lining to the story If you thought that I Would turn and run Then y'all don't know me May my fears rest in peace 'Cause that's the old me Got this taste on my tongue I crave the glory",
          },
          {
            id: 3,
            name:"Mic Drop",
            imgUrl:'https://m.media-amazon.com/images/I/716P+pP7sfL._SS500_.jpg',
            duration: "3 min 30 seg",
            artist: "Manic Drive",
            lyrics: "Oh, make way for the crew Bust down that door Turning heads as they break their necks You know Oh, all eyes on us And your jaw bone hits the floor Hello, I don't think we've ever met before We them boys from the six (mh-hmm) Watch it as we drop it like this (hummm)",
          },
          {
            id: 4,
            name:"Army",
            imgUrl:'https://cdns-images.dzcdn.net/images/cover/729df8dabcc8929e079857164817891a/350x350.jpg',
            duration: "3 min 46 seg",
            artist: "Zyde Wolf",
            lyrics: "I hear the echo out there on the street It's rising up just like a fever dream Cuts like a dagger when I try to breathe The engine's cranking on your war machine You think you got me but you're in too deep You dropped your match into the gasoline",
          },
          {
            id: 5,
            name:"Gladiator",
            imgUrl:'https://lastfm.freetls.fastly.net/i/u/770x0/16c9c5523e1f33351b8538b746b28c9c.jpg',
            duration: "3 min 8 seg",
            artist: "Zyde Wolf",
            lyrics: "Let me back it up to the start of the climb Faced with an army of vipers and lions I had to keep on reaching up 'cause it was my time To tear down the kingdom and call out the liars Got a jail on my heart from the pessimists Got those nails in my mouth for impressionists Spent too much money on a therapist Couldn't fix me, I accepted it",
          },
        ]
    },
    {
        id: 15,
        name:"TRAP",
        creator: "David Ruiz Lara",
        imgUrl:'https://i.scdn.co/image/ab67616d0000b273988ede5e1276e758b5f9e577',
	      duration: "10h 41m",
        songs:[
          {
            id: 1,
            name:"Safaera",
            imgUrl:'https://i.pinimg.com/564x/05/1c/b9/051cb92fd7b53a6e450b1f6891622c57.jpg',
            duration: "4 min 55seg",
            artist: "Bad Bunny",
            lyrics: "Bla, bla, bla, bla, bla, bla y, yo, yo-yo, yo-yo, yo-yo Yo, (la-la-la-la-la-la-la) blow, blow (la-la-la-la-la-la-la) Diablo', qué safaera' Tú tiene' un culo cabrón Cualquier cosa que te pongas rompes la carretera (la-la-la-la-la) Aight, muévelo, muévelo, muévelo, muévelo (la-la-la-la-la-la-la) Qué safaera' (la-la-la-la-la) Tú tiene' un culo cabrón Cualquier cosa que te pongas rompes la carretera Aight, (tra) muévelo, muévelo, muévelo, muévelo",
          },
          {
            id: 2,
            name:"Kool Aid & Frozen Pizza",
            imgUrl:'https://www.mor.bo/wp-content/uploads/2020/05/kids.jpg',
            duration: "2 min 38 seg",
            artist: "Mac Miller",
            lyrics: "Kids Hey Kool-Aid and frozen pizza It's a work of art, I ain't talking Mona Lisa Dream of rocking crowds, see me filling up arenas This weed got me laughing like a damn hyena (ha) Yeah, I live a life pretty similar to yours Used to go to school, hang with friends and play sports Every single summer taking trips to the shore And that was all gravy but I knew I wanted more",
          },
          {
            id: 3,
            name:"Warriors",
            imgUrl:'https://lastfm.freetls.fastly.net/i/u/770x0/aed5e019e5f1419ec199a6f1ec658983.jpg',
            duration: "3 min 24 seg",
            artist: "League of Legends",
            lyrics: "As a child you would wait And watch from far away But you always knew that you'd be the one That work while they all play In youth you'd lay Awake at night and scheme Of all the things that you would change But it was just a dream! Here we are, don't turn away now, We are the warriors that built this town Here we are, don't turn away now We are the warriors that built this town From dust.",
          },
          {
            id: 4,
            name:"I Bet You Look Good on the Dancefloor",
            imgUrl:'https://www.nacionrock.com/wp-content/uploads/arctic.jpg',
            duration: "2 min 54 seg",
            artist: "Arctic Monkeys",
            lyrics: "Stop making the eyes at me I'll stop making the eyes at you What it is that surprises me Is that I don't really want you to And your shoulders are frozen (cold as the night) Oh, but you're an explosion (you're dynamite) Your name isn't Rio, but I don't care for sand And lighting the fuse might result in a bang, b-b-bang-oh",
          },
          {
            id: 5,
            name:"Oceans",
            imgUrl:'https://img.discogs.com/obDk-GqUX2h_B5fXMhgWoZA-95A=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-12922991-1544606338-6439.jpeg.jpg',
            duration: "3 min 36 seg",
            artist: "Seafret",
            lyrics: "I want you Yeah I want you And nothing comes close To the way that I need you I wish I can feel your skin And I want you From somewhere within It feels like there's oceans Between me and you once again We hide our emotions Under the surface and tryin' to pretend But it feels like there's oceans Between you and me",
          },
        ]
    },
    {
      id: 16,
      name:"Fiesta",
      creator: "David Ruiz Lara",
      imgUrl:'https://images.genius.com/573a07cba6e81c8bf69f279565093eca.1000x1000x1.png',
      duration: "10h 41m",
      songs:[
        {
          id: 1,
          name:"Yonaguni",
          description:"descripcion",
          imgUrl:'https://images.genius.com/573a07cba6e81c8bf69f279565093eca.1000x1000x1.png',
          duration: "3 min 26 seg",
          artist: "Bad Bunny",
          lyrics: "Aunque sé que no debo, ey Pensar en ti, bebé, pero cuando bebo Me viene tu nombre, tu cara Tu risa y tu pelo, ey Dime dónde tú está', que yo por ti cojo un vuelo Y a Yonaguni le llego, ey No me busque' en Instagram Mami, búscame en casa Pa' que vea' lo que pasa, ey Si tú me prueba', te casa', ey Ese cabrón ni te abraza Y yo loco por tocarte Pero ni me atrevo a textearte Tú con cualquier outfit la parte' Mami, tú ere' aparte Shorty, tiene' un culo bien grande, eh De-demasiao' grande Y yo lo tengo estudiao', ya mismo me gradúo Y en la cara me lo tatúo Vi que viste mi story y subiste una pa' mí Yo que me iba a dormir, ey En la disco habían mil Y yo bailando contigo en mi mente Aunque sé que no debo Pensar en ti, bebé, pero cuando bebo Me viene tu nombre, tu cara Tu risa y tu pelo, ey Dime dónde tú está', que yo por ti cojo un vuelo Y a Yonaguni le llego",
        },
        {
          id: 2,
          name:"Peppas",
          imgUrl:'https://cdns-images.dzcdn.net/images/cover/1b88acc901e3beff139b5b4eea025802/500x500.jpg',
          duration: "4 min 47 seg",
          artist: "Farruko",
          lyrics: "No me importa lo que de mí se diga Vida usted su vida, que yo vivo la mía Que solo es una, disfruta el momento Que el tiempo se acaba y pa'trás no vira Bebiendo, fumando y jodiendo Sigo vacilando de party to' los día' Síguelo, oh-oh-oh, oh-oh-oh, oh-oh (Farru) Síguelo, oh-oh-oh, oh-oh-oh, oh-oh (la rola y pepa)",
        },
        {
          id: 3,
          name:"Todo de ti",
          imgUrl:'https://i.scdn.co/image/ab67616d0000b273c1449d5655128274517f3733',
          duration: "3 min 19 seg",
          artist: "Rauw Alejandro",
          lyrics: "Aceleraste mis latidos Es que me gusta todo de ti De to'as tus partes, ¿cuál decido? Es que me gusta todo de ti Es que me gusta todo de ti Es que me gusta todo de ti",
        },
        {
          id: 4,
          name:"DÁKITI",
          imgUrl:'https://i.scdn.co/image/ab67616d0000b273005ee342f4eef2cc6e8436ab',
          duration: "3 min 25 seg",
          artist: "Bad Bunny, Jhay Cortez",
          lyrics: "Baby, ya yo me enteré, se nota cuando me ve' Ahí donde no has llegao' sabes que yo te llevaré Y dime qué quieres beber, es que tú eres mi bebé ¿Y de nosotros quién va a hablar? Si no nos dejamos ver",
        },
        {
          id: 5,
          name:"My Universe",
          imgUrl:'https://m.media-amazon.com/images/I/A1-7A-nbtOS._SS500_.jpg',
          duration: "3 min 46 seg",
          artist: "Coldplay, BTS",
          lyrics: "In the night, I lie and look up at you When the morning comes, I watch you rise There's a paradise they couldn't capture That bright infinity inside your eyes 매일 밤 네게 날아가 (가)꿈이란 것도 잊은 채나 웃으며 너를 만나 (나) Never-ending forever, baby",
        },
      ]
  },

]